openapi: 3.0.0
info:
  title: Blog Posts API
  version: 1.0.0
  description: API voor het beheren van blogposts

paths:
  /api/posts:
    get:
      summary: Lijst van alle posts
      responses:
        '200':
          description: Een lijst van posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
    post:
      summary: Nieuwe post maken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostInput'
      responses:
        '201':
          description: Post aangemaakt
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'

  /api/posts/{id}:
    get:
      summary: Details van een post
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Details van de post
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '404':
          description: Post niet gevonden
    put:
      summary: Post bijwerken
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostInput'
      responses:
        '200':
          description: Post bijgewerkt
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '404':
          description: Post niet gevonden
    delete:
      summary: Post verwijderen
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Post verwijderd
        '404':
          description: Post niet gevonden

components:
  schemas:
    Post:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        content:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    PostInput:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
      required:
        - title
        - content
